from pptx import Presentation
from pptx.util import Inches, Pt

def create_ppt(slides_text: str, filename="presentation.pptx"):
    """
    Convert slide outline text into a real .pptx file.
    The input is the slides outline generated by writer_agent.
    """

    prs = Presentation()

    # Split slides based on line breaks
    slide_blocks = slides_text.strip().split("\n\n")

    for block in slide_blocks:
        lines = [l.strip() for l in block.split("\n") if l.strip()]

        if not lines:
            continue

        title = lines[0].replace("Slide", "").replace(":", "").strip()
        bullets = lines[1:]

        # Add slide layout (Title + Content)
        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)

        # Set title
        slide_title = slide.shapes.title
        slide_title.text = title

        # Set content bullets
        body = slide.placeholders[1].text_frame
        body.clear()

        for bullet_text in bullets:
            p = body.add_paragraph()
            p.text = bullet_text
            p.level = 0

    prs.save(filename)
    return filename
